using System.ComponentModel.DataAnnotations;

namespace Oje.Infrastructure.Enums
{
    public enum BlockClientConfigType
    {
        [Display(Name = "استعلام ثالث")]
        CarThirdInquiry = 1,
        [Display(Name = "استعلام بدنه")]
        CarBodyInquiry = 2,
        [Display(Name = "استعلام آتش سوزی")]
        FireInsuranceInquiry = 3,
        [Display(Name = "ایجاد فرم پیشنهاد")]
        CreateProposalFilledForm = 4,
        [Display(Name = "ثبت نظر برای بلاگ")]
        BlogReview = 5,
        [Display(Name = "پسندیدن بلاگ")]
        LikeBlog = 7,
        [Display(Name = "ثبت یادآوری فرم پیشنهاد")]
        CreateNewProposalFormReminder = 9,
        [Display(Name = "ورود با اس ام اس")]
        LoginWithSMS = 10,
        [Display(Name = "ورود با کلمه عبور")]
        LoginWithPassword = 11,
        [Display(Name = "بازیابی کلمه عبور با پیامک")]
        ActiveCodeForResetPassword = 12,
        [Display(Name = "برسی صحت کد پیامک شده برای بازیابی کلمه عبور")]
        CheckIfSmsCodeIsValid = 13,
        [Display(Name = "تغییر کلمه عبور بعد از برسی صحت کد پیامک شده")]
        ChangePasswordAndLogin = 14,
        [Display(Name = "عدم پیدا کردن صفحه")]
        PageNotFound = 15,
        [Display(Name = "تماس با ما")]
        ContactUs = 16,
        [Display(Name = "پیش ثبت نام کاربر")]
        CreateUserPreRegister = 17,
        [Display(Name = "استعلام ثبت خسارت")]
        ContractValidationCheck = 18,
        [Display(Name = "ثبت اعلام خسارت در وبسایت")]
        ContractCreate = 19,
        [Display(Name = "افزودن مدرک جدید برای خسارت")]
        WebsiteUserAddNewImageForInsuranceContract = 20,
        [Display(Name = "ثبت مدرک جدید برای فرم پیشنهاد ها در وبسایت")]
        NewDocumentForWebUserPPF = 21,
        [Display(Name = "ایجاد تیکت")]
        CreateNewTicket = 22,
        [Display(Name = "ایجاد پاسخ برای تیکت")]
        CreateNewAnswerForTicket = 23,
        [Display(Name = "ثبت ایمیل جدید توسط چت انلاین")]
        SubscribeNewEmail = 24,
        [Display(Name = "بارگزاری فایل برای انلاین چت")]
        UploadFileForOnlineChat = 25,
        [Display(Name = "بارگزاری فایل صوتی برای چت انلاین")]
        UploadVoiceForOnlineChat = 26,
        [Display(Name = "جوین شدن در روم جهت چت")]
        JoinOnlineRome = 27,
        [Display(Name = "ارسال پیام در چت برای چت")]
        SendMessage = 28,
        [Display(Name = "ارسال نقشه برای کاربر برای چت")]
        SendMapForUser = 29,
        [Display(Name = "ارسال صدا برای کاربر برای چت")]
        SendVoiceForUser = 30,
        [Display(Name = "بارگزاری فایل برای ادمین برای چت")]
        UploadVoiceForAdmin = 31,
        [Display(Name = "ارسال نقشه برای ادمین برای چت")]
        SendMapForAdmin = 32,
        [Display(Name = "بارگزاری فایل برای کاربر چت")]
        UploadFileForUser = 33,
        [Display(Name = "بارگزاری فایل برای ادمین برای چت")]
        UploadFileForAdmin = 34,
        [Display(Name = "ارسال پیام برای ادمین برای چت")]
        SendMessageForAdmin = 35,
        [Display(Name = "عضویت برای وب نوتیفیکیشن")]
        ExternalNotificationServicePushSubscription = 36,
        [Display(Name =  "به روز رسانی اطلاعت پروفایل کاربر")]
        UpdateUserProfile = 37,
        [Display(Name = "افزودن مناقصه")]
        CreateTender = 38,
        [Display(Name = "ورود/ثبت نام با کد پیامک")]
        LoginRegister = 39,
        [Display(Name = "دریافت اطلاعات کاربر هنگام ثبت نام")]
        GetUserInfoRegister = 40,
        [Display(Name = "کارت به کارت ثبت نام کاربر")]
        RegisterCardPayment = 41,
        [Display(Name = "دانلود پی دی اف ثبت نام")]
        RegisterDownloadPDF = 42,
        [Display(Name = "اضافه کردن دستی در فایروال (استفاده نشود)")]
        ManualAdded = 43,
        [Display(Name = "استعلام بر اساس پلاک و کد ملی ثالث")]
        CarThirdPlaqueInquiry = 44,
        [Display(Name = "ثبت فرم عمومی")]
        CreateGeneralForms = 45,
        [Display(Name = "ثبت خسارت اعتبار سنجی کد پیامکی")]
        ContractValidationSMSCheck = 46,
        [Display(Name = "کد تایید جهت ایجاد درخواست درمان")]
        ContractCreateConfirmSMS = 47,
    }
}
